export const REDIS ='REDIS';

// PREFIX
export const AUTH_KEY_PREFIX='auth:'
export const SESSION_KEY_PREFIX=`${AUTH_KEY_PREFIX}sessions:`
export const SESSION_TRACK_USER_SESSION_KEY_PREFIX=`${SESSION_KEY_PREFIX}user:`
export const SESSION_SESSION_ID_KEY_PREFIX=`${SESSION_KEY_PREFIX}sid:`
export const SESSION_SESSION_TOKEN_ACCESS_KEY_PREFIX=`${SESSION_KEY_PREFIX}st:sta:`
export const SESSION_SESSION_CONTINUOUS_TOKEN_KEY_PREFIX=`${SESSION_KEY_PREFIX}st:sct:`

export const CONFIRM_EMAIL_KEY=`${AUTH_KEY_PREFIX}confirm-email:`
