// QUEUES

export const RABBITMQ_AUTH_QUEUE='AUTH_QUEUE'
export const RABBITMQ_USER_QUEUE='USER_QUEUE'
export const RABBITMQ_ACCOUNT_QUEUE='ACCOUNT_QUEUE'
export const RABBITMQ_MAILING_QUEUE='MAILING_QUEUE'

// SERVICES

export const USER_SERVICE='USER_SERVICE'
export const AUTH_SERVICE='AUTH_SERVICE'
export const ACCOUNT_SERVICE='ACCOUNT_SERVICE'
export const MAILING_SERVICE='MAILING_SERVICE'
